# Generated by Django 6.0 on 2025-12-14 22:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('equipmentName', models.CharField(max_length=100)),
                ('equipmentSerialNumber', models.CharField(max_length=100)),
                ('borrowerName', models.CharField(max_length=100)),
                ('borrowerEmail', models.EmailField(blank=True, max_length=254)),
                ('checkoutDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('returned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('equipmentType', models.CharField(choices=[('scope', 'Oscilloscope'), ('mcu', 'Microcontroller'), ('sensor', 'Sensor'), ('psu', 'Power Supply'), ('fpga', 'Field Programmable Gate Array'), ('other', 'Other')], max_length=50)),
                ('serialNumber', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
    ]
