# Generated by Django 6.0 on 2025-12-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='equipmentType',
            field=models.CharField(choices=[('scope', 'Oscilloscope'), ('mcu', 'Microcontroller'), ('sensor', 'Sensor'), ('psu', 'Power Supply'), ('fpga', 'Field Programmable Gate Array'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
